export const CAPITAL_COPY = {
  title: 'Capital',
  statusEmpty: 'Sin sync',
  statusReady: 'Listo',
  statusSyncing: 'Sincronizando',
  statusUpdatedPrefix: 'Actualizado',
  statusError: 'Error al sincronizar',
  activeValueTitle: 'Equity actual',
  netCapitalTitle: 'Capital neto',
  pnlTitle: 'PnL historico',
  aprTitle: 'XIRR historico',
  vaultsTitle: 'Vaults',
  settingsTitle: 'Hyperliquid',
  walletLabel: 'Wallet',
  vaultLabel: 'Vault',
  vaultPlaceholder: 'Opcional si la wallet tiene vaults',
  syncLabel: 'Sincronizar',
  subscribedVaultsTitle: 'Vaults suscritos',
  movementsTitle: 'Movimientos',
  emptyVaults: 'Sin vaults sincronizados',
  emptyMovements: 'Sin movimientos sincronizados',
  vaultHeaders: [
    'Vault',
    'Equity',
    'Capital activo',
    'PnL activo',
    'APR activo',
    'Lockup',
  ] as const,
  movementHeaders: ['Hora / fecha', 'Tipo', 'Monto'] as const,
  depositLabel: 'Deposito',
  withdrawalLabel: 'Retiro',
};
