export const CAPITAL_COPY = {
  title: 'Capital',
  contextTitle: 'Capital',
  contextMetaPrefix: 'Hyperliquid',
  statusEmpty: 'Sin sync',
  statusReady: 'Listo',
  statusSyncing: 'Sincronizando',
  statusUpdatedPrefix: 'Actualizado',
  statusError: 'Error al sincronizar',
  activeValueTitle: 'Equity actual',
  pnlContext: 'PnL histórico sobre capital neto',
  netCapitalTitle: 'Capital neto',
  netCapitalSub: 'USDC aportado',
  aprTitle: 'XIRR historico',
  aprSub: 'anualizado por flujos',
  vaultsTitle: 'Vaults suscritos',
  vaultsSub: 'posiciones abiertas',
  movementsCountTitle: 'Movimientos',
  movementsCountSub: 'depósitos y retiros',
  connectionTitle: 'Conexión Hyperliquid',
  connectionNote: 'Consulta pública de solo lectura. No se guardan claves.',
  walletLabel: 'Wallet',
  vaultLabel: 'Vault',
  vaultLabelOptional: 'opcional',
  vaultPlaceholder: 'Se deduce de la wallet',
  syncLabel: 'Sincronizar',
  subscribedVaultsTitle: 'Vaults suscritos',
  subscribedVaultsNote: 'Ordenados por equity',
  movementsTitle: 'Movimientos',
  emptyVaults: 'Sin vaults sincronizados',
  emptyMovements: 'Sin movimientos sincronizados',
  vaultHeaders: [
    'Vault',
    'Equity',
    'Capital activo',
    'PnL activo',
    'APR activo',
    'Lockup',
  ] as const,
  vaultColumnWidths: ['22%', '15%', '18%', '16%', '14%', '15%'] as const,
  vaultHeaderAlign: [false, true, true, true, true, false] as const,
  movementHeaders: ['Fecha', 'Tipo', 'Monto'] as const,
  movementColumnWidths: ['34%', '30%', '36%'] as const,
  movementHeaderAlign: [false, false, true] as const,
  depositLabel: 'Deposito',
  withdrawalLabel: 'Retiro',
};
